import * as fs from 'fs';
import * as path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

const webDistDir = path.resolve(__dirname, '..', 'dist', 'web');
const outputFile = path.resolve(__dirname, '..', 'src', 'cli', 'commands', 'webAssets.ts');

const MIME_MAP = {
  '.html': 'text/html; charset=utf-8',
  '.css': 'text/css; charset=utf-8',
  '.js': 'application/javascript; charset=utf-8',
  '.svg': 'image/svg+xml',
  '.json': 'application/json',
  '.png': 'image/png',
  '.ico': 'image/x-icon',
};

function getFilesRecursively(dir, baseDir = dir) {
  let results = [];
  if (!fs.existsSync(dir)) return results;
  const list = fs.readdirSync(dir);
  for (const file of list) {
    const fullPath = path.join(dir, file);
    const stat = fs.statSync(fullPath);
    if (stat && stat.isDirectory()) {
      results = results.concat(getFilesRecursively(fullPath, baseDir));
    } else {
      const relPath = '/' + path.relative(baseDir, fullPath).split(path.sep).join('/');
      results.push({ fullPath, relPath });
    }
  }
  return results;
}

const files = getFilesRecursively(webDistDir);
const assetMap = {};

for (const { fullPath, relPath } of files) {
  const ext = path.extname(fullPath).toLowerCase();
  const contentType = MIME_MAP[ext] || 'application/octet-stream';
  const isBinary = ['.png', '.ico', '.jpg', '.jpeg', '.wasm'].includes(ext);

  if (isBinary) {
    const data = fs.readFileSync(fullPath).toString('base64');
    assetMap[relPath] = { contentType, content: data, isBase64: true };
  } else {
    const data = fs.readFileSync(fullPath, 'utf-8');
    assetMap[relPath] = { contentType, content: data, isBase64: false };
  }
}

const tsContent = `// Auto-generated by scripts/embed-web.js — DO NOT EDIT DIRECTLY
export interface EmbeddedAsset {
  contentType: string;
  content: string;
  isBase64: boolean;
}

export const EMBEDDED_WEB_ASSETS: Record<string, EmbeddedAsset> = ${JSON.stringify(assetMap, null, 2)};
`;

fs.writeFileSync(outputFile, tsContent, 'utf-8');
console.log(`Embedded ${files.length} web assets into ${outputFile}`);
